# claude sonnet 4

services:
  - type: web
    name: county-health-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0